GET http://localhost:3000/api/journal

###

POST http://localhost:3000/api/journal/entry
Content-Type: application/json

{
    "title": "Thist was the new party princess",
    "entry": "And she was going on and on about her drunken charades"
}

###

DELETE http://localhost:3000/api/journal/63ee7473c4d96ccae2d5d1c3 